### ISSUE TITLE
Implement Page Replacement Policies in Buffer Manager 

### ISSUE THREAD

**Issue by Anthony4m** [Anthony4m/awesomeDB#15]
**Description:**  
Add support for page eviction strategies to the buffer manager.  
**Tasks:**  
- [x] Implement Least Recently Used (LRU) policy.  
- [x] Add support for Clock algorithm as an alternative.  
- [x] Evaluate policies for database workloads (e.g., sequential scans).  
- [x] Make eviction policy configurable.

**Comment by Anthony4m** [comment]
Implement the strategy pattern and make the replacement algorithm configurable
